import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Search, 
  Fish, 
  Sparkles, 
  Users, 
  MessageSquare, 
  TrendingUp, 
  ArrowRight,
  RefreshCcw,
  AlertCircle,
  ChevronRight,
  History,
  Share2,
  Copy,
  Check,
  Trash2,
  Clock,
  Download,
  Globe
} from 'lucide-react';
import { Agent, Message, SimulationState, HistoryItem } from './types';
import { generateAgents, simulateDebate, synthesizeForesight } from './services/gemini';

const LANGUAGES = [
  { label: 'English', value: 'English' },
  { label: 'Hindi (हिन्दी)', value: 'Hindi' },
  { label: 'Bengali (বাংলা)', value: 'Bengali' },
  { label: 'Tamil (தமிழ்)', value: 'Tamil' },
  { label: 'Telugu (తెలుగు)', value: 'Telugu' },
  { label: 'Marathi (मराठी)', value: 'Marathi' },
  { label: 'Gujarati (ગુજરાતી)', value: 'Gujarati' },
  { label: 'Kannada (ಕನ್ನಡ)', value: 'Kannada' },
  { label: 'Malayalam (മലയാളം)', value: 'Malayalam' },
  { label: 'Punjabi (ਪੰਜਾਬੀ)', value: 'Punjabi' },
  { label: 'Spanish', value: 'Spanish' },
  { label: 'French', value: 'French' },
  { label: 'German', value: 'German' },
];

export default function App() {
  const [state, setState] = useState<SimulationState>({
    status: 'idle',
    question: '',
    language: 'English',
    agents: [],
    messages: [],
    history: [],
  });

  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Load history from localStorage
  useEffect(() => {
    const savedHistory = localStorage.getItem('mirofish_history');
    if (savedHistory) {
      try {
        setState(prev => ({ ...prev, history: JSON.parse(savedHistory) }));
      } catch (e) {
        console.error("Failed to parse history", e);
      }
    }
  }, []);

  // Save history to localStorage
  useEffect(() => {
    localStorage.setItem('mirofish_history', JSON.stringify(state.history));
  }, [state.history]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    if (state.status === 'simulating') {
      scrollToBottom();
    }
  }, [state.messages]);

  const exportToTxt = (question: string, agents: Agent[], messages: Message[], synthesis: string) => {
    const content = `
MIROFISH FORESIGHT REPORT
-------------------------
Date: ${new Date().toLocaleString()}
Inquiry: ${question}

DIGITAL SOCIETY (AGENTS):
${agents.map(a => `- ${a.name} (${a.role})`).join('\n')}

DEBATE TRANSCRIPT:
${messages.map(m => {
  const agent = agents.find(a => a.id === m.agentId);
  return `[${agent?.name}]: ${m.content}`;
}).join('\n\n')}

FINAL FORESIGHT:
${synthesis}

-------------------------
Generated by MiroFish Systems
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `mirofish-foresight-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleStartSimulation = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!state.question.trim()) return;

    setState(prev => ({ ...prev, status: 'initializing', agents: [], messages: [], synthesis: undefined }));

    try {
      const agents = await generateAgents(state.question, state.language);
      setState(prev => ({ ...prev, status: 'simulating', agents }));

      const messages = await simulateDebate(state.question, agents, state.language);
      
      // Simulate typing/delay for each message
      for (let i = 0; i < messages.length; i++) {
        await new Promise(resolve => setTimeout(resolve, 1500));
        setState(prev => ({
          ...prev,
          messages: [...prev.messages, messages[i]]
        }));
      }

      setState(prev => ({ ...prev, status: 'synthesizing' }));
      const synthesis = await synthesizeForesight(state.question, messages, agents, state.language);
      
      const newHistoryItem: HistoryItem = {
        id: Date.now().toString(),
        question: state.question,
        agents,
        messages,
        synthesis,
        timestamp: Date.now(),
      };

      setState(prev => ({ 
        ...prev, 
        status: 'completed', 
        synthesis,
        history: [newHistoryItem, ...prev.history].slice(0, 20) // Keep last 20
      }));

      // Auto Export
      exportToTxt(state.question, agents, messages, synthesis);

    } catch (error) {
      console.error(error);
      setState(prev => ({ ...prev, status: 'error', error: 'The digital society encountered a disruption. Please try again.' }));
    }
  };

  const loadFromHistory = (item: HistoryItem) => {
    setState(prev => ({
      ...prev,
      status: 'completed',
      question: item.question,
      agents: item.agents,
      messages: item.messages,
      synthesis: item.synthesis,
    }));
    setIsHistoryOpen(false);
  };

  const deleteHistoryItem = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setState(prev => ({
      ...prev,
      history: prev.history.filter(item => item.id !== id)
    }));
  };

  const copyToClipboard = () => {
    if (state.synthesis) {
      navigator.clipboard.writeText(state.synthesis);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const reset = () => {
    setState(prev => ({
      ...prev,
      status: 'idle',
      question: '',
      agents: [],
      messages: [],
      synthesis: undefined,
    }));
  };

  return (
    <div className="min-h-screen bg-[#0a0502] text-[#e0d8d0] font-sans selection:bg-[#ff4e00] selection:text-white overflow-x-hidden">
      {/* Dynamic Background */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-[#3a1510] rounded-full blur-[120px] opacity-30 animate-pulse" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-[#ff4e00] rounded-full blur-[150px] opacity-10" />
      </div>

      {/* History Sidebar */}
      <AnimatePresence>
        {isHistoryOpen && (
          <>
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsHistoryOpen(false)}
              className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[100]"
            />
            <motion.div 
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="fixed right-0 top-0 bottom-0 w-full max-w-sm bg-[#150d0a] border-l border-white/10 z-[101] shadow-2xl p-8 flex flex-col"
            >
              <div className="flex items-center justify-between mb-8">
                <h3 className="text-xl font-bold uppercase tracking-widest flex items-center gap-2">
                  <Clock className="w-5 h-5 text-[#ff4e00]" /> Remembered
                </h3>
                <button onClick={() => setIsHistoryOpen(false)} className="opacity-40 hover:opacity-100 transition-opacity">
                  <ChevronRight className="w-6 h-6" />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto space-y-4 pr-2">
                {state.history.length === 0 ? (
                  <div className="text-center py-12 opacity-30 italic text-sm">No foresight history yet.</div>
                ) : (
                  state.history.map((item) => (
                    <div 
                      key={item.id}
                      onClick={() => loadFromHistory(item)}
                      className="bg-white/5 border border-white/5 p-4 rounded-2xl cursor-pointer hover:bg-white/10 hover:border-white/20 transition-all group relative"
                    >
                      <div className="text-xs opacity-40 mb-2">{new Date(item.timestamp).toLocaleDateString()}</div>
                      <div className="text-sm font-medium line-clamp-2 italic font-serif">"{item.question}"</div>
                      <div className="flex gap-2 mt-2">
                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            exportToTxt(item.question, item.agents, item.messages, item.synthesis);
                          }}
                          className="p-1.5 bg-white/5 hover:bg-white/20 rounded-lg transition-colors"
                          title="Export to TXT"
                        >
                          <Download className="w-3 h-3" />
                        </button>
                        <button 
                          onClick={(e) => deleteHistoryItem(item.id, e)}
                          className="p-1.5 bg-white/5 hover:bg-red-500/20 hover:text-red-500 rounded-lg transition-colors"
                          title="Delete"
                        >
                          <Trash2 className="w-3 h-3" />
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      <main className="relative z-10 max-w-5xl mx-auto px-6 py-12 min-h-screen flex flex-col">
        {/* Header */}
        <header className="flex items-center justify-between mb-16">
          <div className="flex items-center gap-3 group cursor-pointer" onClick={reset}>
            <div className="w-10 h-10 bg-[#ff4e00] rounded-xl flex items-center justify-center shadow-[0_0_20px_rgba(255,78,0,0.4)] group-hover:scale-110 transition-transform">
              <Fish className="text-white w-6 h-6" />
            </div>
            <h1 className="text-2xl font-bold tracking-tighter uppercase italic">MiroFish</h1>
          </div>
          <div className="flex items-center gap-6">
            <button 
              onClick={() => setIsHistoryOpen(true)}
              className="text-xs uppercase tracking-[0.2em] opacity-40 hover:opacity-100 flex items-center gap-2 transition-opacity"
            >
              <History className="w-4 h-4" /> History
            </button>
            <div className="text-xs uppercase tracking-[0.2em] opacity-40 font-mono hidden md:block">
              {state.status === 'idle' ? 'System Ready' : `Status: ${state.status}`}
            </div>
          </div>
        </header>

        <AnimatePresence mode="wait">
          {state.status === 'idle' && (
            <motion.div
              key="idle"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="flex-1 flex flex-col justify-center items-center text-center"
            >
              <h2 className="text-5xl md:text-7xl font-light leading-tight mb-8 tracking-tight">
                Gain <span className="italic font-serif text-[#ff4e00]">foresight</span> in a <br />
                world of noise.
              </h2>
              <p className="max-w-xl text-lg opacity-60 mb-12 leading-relaxed">
                Feed in your data or a pressing question. Watch as a digital society springs to life to reveal hidden truths before they happen.
              </p>

              <div className="w-full max-w-2xl flex flex-col gap-4">
                <div className="flex items-center justify-center gap-4 mb-2">
                  <div className="flex items-center gap-2 bg-white/5 border border-white/10 rounded-full px-4 py-2">
                    <Globe className="w-4 h-4 text-[#ff4e00]" />
                    <select 
                      value={state.language}
                      onChange={(e) => setState(prev => ({ ...prev, language: e.target.value }))}
                      className="bg-transparent text-xs uppercase tracking-widest font-bold focus:outline-none cursor-pointer"
                    >
                      {LANGUAGES.map(lang => (
                        <option key={lang.value} value={lang.value} className="bg-[#150d0a]">{lang.label}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <form onSubmit={handleStartSimulation} className="relative group">
                  <input
                    type="text"
                    value={state.question}
                    onChange={(e) => setState(prev => ({ ...prev, question: e.target.value }))}
                    placeholder="What is the future of..."
                    className="w-full bg-white/5 border border-white/10 rounded-2xl px-8 py-6 text-xl focus:outline-none focus:border-[#ff4e00]/50 focus:bg-white/10 transition-all pr-20 shadow-2xl backdrop-blur-xl"
                  />
                  <button
                    type="submit"
                    disabled={!state.question.trim()}
                    className="absolute right-3 top-3 bottom-3 px-6 bg-[#ff4e00] text-white rounded-xl flex items-center justify-center hover:bg-[#ff6a26] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <ArrowRight className="w-6 h-6" />
                  </button>
                </form>
              </div>
              
              <div className="mt-12 flex gap-8 text-xs uppercase tracking-widest opacity-30">
                <div className="flex items-center gap-2"><Users className="w-4 h-4" /> 1000+ Analysts</div>
                <div className="flex items-center gap-2"><TrendingUp className="w-4 h-4" /> Market Synthesis</div>
                <div className="flex items-center gap-2"><Sparkles className="w-4 h-4" /> AI Foresight</div>
              </div>
            </motion.div>
          )}

          {(state.status === 'initializing' || state.status === 'simulating' || state.status === 'synthesizing' || state.status === 'completed') && (
            <motion.div
              key="simulation"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex-1 flex flex-col gap-8"
            >
              {/* Simulation Header */}
              <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-md">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <span className="text-xs uppercase tracking-widest text-[#ff4e00] font-bold">Inquiry</span>
                    <span className="text-[10px] bg-white/10 px-2 py-0.5 rounded-full opacity-60">{state.language}</span>
                  </div>
                  <div className="flex items-center gap-4">
                    <button onClick={reset} className="text-xs opacity-40 hover:opacity-100 flex items-center gap-1 transition-opacity">
                      <RefreshCcw className="w-3 h-3" /> New Inquiry
                    </button>
                  </div>
                </div>
                <h3 className="text-2xl font-medium italic font-serif">"{state.question}"</h3>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 flex-1">
                {/* Agents List */}
                <div className="lg:col-span-1 flex flex-col gap-4">
                  <h4 className="text-xs uppercase tracking-widest opacity-40 mb-2">Digital Society</h4>
                  {state.agents.length === 0 ? (
                    <div className="flex flex-col gap-4">
                      {[1, 2, 3, 4, 5].map(i => (
                        <div key={i} className="h-16 bg-white/5 rounded-2xl animate-pulse" />
                      ))}
                    </div>
                  ) : (
                    state.agents.map((agent) => (
                      <motion.div
                        key={agent.id}
                        initial={{ x: -20, opacity: 0 }}
                        animate={{ x: 0, opacity: 1 }}
                        className="bg-white/5 border border-white/5 p-4 rounded-2xl flex items-center gap-4 group hover:bg-white/10 transition-colors"
                      >
                        <div 
                          className="w-10 h-10 rounded-full flex-shrink-0 overflow-hidden border-2"
                          style={{ borderColor: agent.color }}
                        >
                          <img src={agent.avatar} alt={agent.name} referrerPolicy="no-referrer" />
                        </div>
                        <div>
                          <div className="font-bold text-sm">{agent.name}</div>
                          <div className="text-[10px] uppercase tracking-wider opacity-40">{agent.role}</div>
                        </div>
                      </motion.div>
                    ))
                  )}
                </div>

                {/* Debate Feed */}
                <div className="lg:col-span-2 flex flex-col gap-4 bg-white/[0.02] border border-white/5 rounded-3xl p-6 h-[500px] overflow-y-auto scrollbar-hide relative">
                  <h4 className="text-xs uppercase tracking-widest opacity-40 mb-2 sticky top-0 bg-[#0a0502]/80 backdrop-blur-sm py-2 z-10 flex justify-between items-center">
                    <span>Live Synthesis (Argue)</span>
                    {state.status === 'completed' && (
                      <div className="flex gap-4">
                        <button 
                          onClick={() => exportToTxt(state.question, state.agents, state.messages, state.synthesis || '')}
                          className="flex items-center gap-2 hover:text-[#ff4e00] transition-colors"
                        >
                          <Download className="w-3 h-3" /> Export TXT
                        </button>
                        <button 
                          onClick={copyToClipboard}
                          className="flex items-center gap-2 hover:text-[#ff4e00] transition-colors"
                        >
                          {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                          {copied ? 'Copied' : 'Copy Debate'}
                        </button>
                      </div>
                    )}
                  </h4>
                  
                  <div className="flex flex-col gap-6">
                    {state.messages.map((msg, idx) => {
                      const agent = state.agents.find(a => a.id === msg.agentId);
                      return (
                        <motion.div
                          key={idx}
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          className="flex gap-4"
                        >
                          <div className="w-8 h-8 rounded-full flex-shrink-0 overflow-hidden mt-1">
                            <img src={agent?.avatar} alt={agent?.name} referrerPolicy="no-referrer" />
                          </div>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1">
                              <span className="text-xs font-bold" style={{ color: agent?.color }}>{agent?.name}</span>
                              <span className="text-[10px] opacity-20">{new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</span>
                            </div>
                            <p className="text-sm leading-relaxed opacity-80">{msg.content}</p>
                          </div>
                        </motion.div>
                      );
                    })}
                    
                    {state.status === 'simulating' && state.messages.length < state.agents.length && (
                      <div className="flex gap-4 animate-pulse">
                        <div className="w-8 h-8 bg-white/10 rounded-full" />
                        <div className="flex-1 space-y-2">
                          <div className="h-3 bg-white/10 rounded w-24" />
                          <div className="h-3 bg-white/10 rounded w-full" />
                        </div>
                      </div>
                    )}

                    {state.status === 'synthesizing' && (
                      <motion.div 
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="flex flex-col items-center justify-center py-12 text-center gap-4"
                      >
                        <div className="w-12 h-12 border-2 border-[#ff4e00] border-t-transparent rounded-full animate-spin" />
                        <div className="text-sm italic font-serif opacity-60">Synthesizing hidden truths...</div>
                      </motion.div>
                    )}

                    {state.status === 'completed' && state.synthesis && (
                      <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="mt-8 bg-[#ff4e00] text-white p-8 rounded-3xl shadow-2xl relative overflow-hidden group"
                      >
                        <div className="absolute top-0 right-0 p-4 opacity-20 group-hover:rotate-12 transition-transform">
                          <Sparkles className="w-12 h-12" />
                        </div>
                        <div className="flex justify-between items-start mb-4">
                          <h5 className="text-xs uppercase tracking-[0.3em] font-bold opacity-80">Final Foresight</h5>
                          <div className="flex gap-2">
                            <button 
                              onClick={() => exportToTxt(state.question, state.agents, state.messages, state.synthesis || '')}
                              className="p-2 bg-black/20 hover:bg-black/40 rounded-lg transition-colors"
                              title="Export to TXT"
                            >
                              <Download className="w-4 h-4" />
                            </button>
                            <button 
                              onClick={copyToClipboard}
                              className="p-2 bg-black/20 hover:bg-black/40 rounded-lg transition-colors"
                              title="Copy Foresight"
                            >
                              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                            </button>
                            <button 
                              className="p-2 bg-black/20 hover:bg-black/40 rounded-lg transition-colors"
                              title="Post/Share"
                            >
                              <Share2 className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                        <div className="text-xl md:text-2xl font-serif italic leading-snug">
                          {state.synthesis}
                        </div>
                        <button 
                          onClick={reset}
                          className="mt-8 flex items-center gap-2 text-xs uppercase tracking-widest font-bold bg-black/20 hover:bg-black/40 px-4 py-2 rounded-full transition-colors"
                        >
                          New Simulation <ChevronRight className="w-4 h-4" />
                        </button>
                      </motion.div>
                    )}
                    <div ref={messagesEndRef} />
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {state.status === 'error' && (
            <motion.div
              key="error"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex-1 flex flex-col items-center justify-center text-center"
            >
              <div className="w-16 h-16 bg-red-500/20 text-red-500 rounded-full flex items-center justify-center mb-6">
                <AlertCircle className="w-8 h-8" />
              </div>
              <h3 className="text-2xl font-bold mb-4">Simulation Disrupted</h3>
              <p className="opacity-60 mb-8 max-w-md">{state.error}</p>
              <button
                onClick={reset}
                className="px-8 py-3 bg-white/10 hover:bg-white/20 rounded-xl transition-colors uppercase tracking-widest text-xs font-bold"
              >
                Try Again
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Footer */}
        <footer className="mt-16 pt-8 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-4 text-[10px] uppercase tracking-widest opacity-30 font-mono">
          <div>&copy; 2026 MiroFish Systems</div>
          <div className="flex gap-6">
            <a href="#" className="hover:opacity-100 transition-opacity">Protocol</a>
            <a href="#" className="hover:opacity-100 transition-opacity">Neural Grid</a>
            <a href="#" className="hover:opacity-100 transition-opacity">Privacy</a>
          </div>
        </footer>
      </main>
    </div>
  );
}
